#!/bin/bash 

set -e

# import openssl library
. functions/openssl.sh

function show_help() {
   echo "$0 -s <SOURCE KEYSTORE> -o <OLD PASSWORD> -n <NEW PASSWORD>"
}

while getopts s:o:n:h opt
do
  case "${opt}" in
    h|\?)
      show_help
      exit 0
      ;;
    s)
      source_keystore=${opt}
      if [[ ${source_keystore}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;
    o)
      old_password=${opt}
      if [[ ${old_password}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;
    n)
      new_password=${opt}
      if [[ ${new_password}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;

  esac
done

change_pkcs12_bundle_password $source_keystore $old_password $new_password
