#!/bin/bash 

# import openssl library
. functions/openssl.sh
. functions/general.sh

function usage() {
   echo "Change the password of a PKCS12 bundle"
   echo "Ex:"
   echo "  $0 -s <SOURCE KEYSTORE> -o <OLD PASSWORD> -n <NEW PASSWORD>"
}

while [ "$1" != "" ]; do
  case $1 in
    -h | --help ) usage
                  exit
                  ;;
    -s | -k | --keystore | --source_keystore ) shift
                                               source_keystore=$1
                                               ;;
    -o | --old_password ) shift
                          old_password=$1
                          ;;
    -n | --new_password ) shift
                          new_password=$1
                          ;;
    * ) usage
        exit 1
    esac
    shift
done

check_param $source_keystore
check_param $old_password
check_param $new_password

change_pkcs12_bundle_password $source_keystore $old_password $new_password
