#!/bin/bash 

set -e

# import openssl library
. functions/openssl.sh

function show_help() {
  echo "Description:\n\t"
  echo "Convert a P12 keystore to a Java keystore store.\n"
  echo "The resulting Java keystore file will then contain your P12 within the default alias: 1\n\n"
  echo "$0 -s <SOURCE KEYSTORE> -d <DESTINATION KEYSTORE> -p <PASSWORD>"
}

while getopts p:s:d:h opt
do
  case "${opt}" in
    h|\?)
      show_help
      exit 0
      ;;
    s)
      source_keystore=${opt}
      if [[ ${source_keystore}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;
    d)
      destination_keystore=${opt}
      if [[ ${destination_keystore}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;
    p)
      password=${opt}
      if [[ ${password}x == "x" ]]; then
	show_help
	exit 1
      fi
  esac
done

convert_p12_to_jks $source_keystore $destination_keystore $password
