#!/bin/bash 
set -e

# import openssl library
source $(dirname $0)/functions/openssl.sh

function show_help() {
  echo "Description:\n\t"
  echo "Create a p12 key\n"
  echo "$0 -s <SOURCE KEYSTORE> -p <PASSWORD>"
}

while getopts p:s:d:h opt
do
  case "${opt}" in
    h|\?)
      show_help
      exit 0
      ;;
    s)
      source_keystore=${opt}
      if [[ ${source_keystore}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;
    p)
      password=${opt}
      if [[ ${password}x == "x" ]]; then
	show_help
	exit 1
      fi
  esac
done

create_pkcs12_key $KEYSTORE ${KEYSTORE}.key $2
