#!/bin/bash 
#
# List a PKCS12 bundle

set -e

# import openssl library
. functions/openssl.sh

KEYSTORE=$1

if [[ -z $KEYSTORE ]]; then
  echo "You need to indicate a keystore"
fi

create_pkcs12_cert $KEYSTORE ${KEYSTORE}.cer $2
