#!/bin/bash 

set -e

# import openssl library
. functions/openssl.sh

function show_help() {
  echo "Description:\n\t"
  echo "Create p12 files from a Java keystore file\n"
  echo "Use this file when converting a truststore to a pem file\n"
  echo "$0 -s <SOURCE KEYSTORE> -p <PASSWORD>\n"
}

while getopts p:s:h opt
do
  case "${opt}" in
    h|\?)
      show_help
      exit 0
      ;;
    s)
      source_keystore=${opt}
      if [[ ${source_keystore}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;
    p)
      password=${opt}
      if [[ ${password}x == "x" ]]; then
	show_help
	exit 1
      fi
      ;;
  esac
done

create_pem_files_from_jks $source_keystore $password
