#!/bin/bash 
#
# List a PKCS12 bundle

set -e

# import openssl library
. functions/openssl.sh

KEYSTORE=$1
PASSWORD=$2

if [[ -z $KEYSTORE ]]; then
  echo "You need to indicate a keystore"
fi

if [[ -z $PASSWORD ]]; then
  echo "You need to indicate a password"
fi

create_pem_files_from_jks $KEYSTORE $PASSWORD
