#!/bin/bash

function usage() {
   echo "Extract the key with RSA password removed and certificate from a PFX or P12 file"
   echo "Ex:"
   echo "  $0 -k <KEYSTORE> -p <PASSWORD>"
}

while [ "$1" != "" ]; do
  case $1 in
    -h | --help ) usage
                  exit
                  ;;
    -s | -k | --keystore | --source_keystore ) shift
                                               keystore=$1
                                               ;;
    -p | --password ) shift
                      password=$1
                      ;;
    * ) usage
        exit 1
    esac
    shift
done

if [[ -z $keystore || -z password ]]; then
  usage
  exit 1
fi

openssl pkcs12 -in "$keystore"  -nocerts -out key.pem -passin pass:${password} -passout pass:${password}
openssl pkcs12 -in "$keystore" -clcerts -nokeys -out cert.pem -passin pass:${password} -passout pass:${password}
openssl rsa -in key.pem -out no.password.key -passin pass:${password} -passout pass:${password}
