#!/bin/bash

function usage() {
  echo "Extract key (.key) and certificate (.crt) from a PFX or PKCS12 file and remove the passphrase"
  echo "Ex:"
  echo "  $0 -k <KEYSTORE> -p <PASSWORD>"
}

while [ "$1" != "" ]; do
  case $1 in
    -h | --help ) usage
                  exit
                  ;;
    -s | -k | --keystore | --source_keystore ) shift
                                               keystore=$1
                                               ;;
    -p | --password ) shift
                      password=$1
                      ;;
    * ) usage
        exit 1
    esac
    shift
done

if [[ -z $keystore || -z $password ]]; then
  usage
  exit 1
fi

openssl pkcs12 -in "$keystore" -nocerts -out "${keystore%.*}.key" -passin pass:"${password}" -passout pass:"${password}"
echo "Created ${keystore%.*}.key"
openssl pkcs12 -in "$keystore" -clcerts -nokeys -out "${keystore%.*}.crt" -passin pass:"${password}" -passout pass:"${password}"
echo "Created ${keystore%.*}.crt"
openssl rsa -in "${keystore%.*}.key" -out "${keystore%.*}.key" -passin pass:"${password}" -passout pass:"${password}"
echo "Removed password from ${keystore%.*}.key"
