#!/bin/bash 
#
# List a PKCS12 bundle

set -e

# import openssl library
. functions/openssl.sh

if [[ -f .password ]]; then
  PASSWORD=$(cat .password)
fi

KEYSTORE=$1

if [[ -z $KEYSTORE ]]; then
  echo "You need to indicate a keystore"
fi

view_pkcs12_bundle $KEYSTORE
